compilation:
  cloud_properties:
    availability_zone: us-west-2a
    ephemeral_disk:
      size: 8192
      type: gp2
    instance_type: m3.large
  network: bolo
  reuse_compilation_vms: true
  workers: 4
director_uuid: 606af3cd-790d-4752-88f2-c1db92732102
disk_pools: []
jobs:
- instances: 1
  name: bolo
  networks:
  - name: bolo
    static_ips:
    - 10.4.1.65
  persistent_disk: 4096
  properties:
    bolo:
      debug: true
      gnossis:
        cached: true
      rrd:
        cached: true
        submission:
          address: 10.4.1.65
        subscription:
          address: 10.4.1.65
      submission:
        address: 10.4.1.65
      subscription:
        address: 10.4.1.65
    dbolo:
      submission:
        address: 10.4.1.65
  resource_pool: small
  templates:
  - name: bolo
    release: bolo
  - name: dbolo
    release: bolo
  - name: rrd
    release: bolo
  - name: gnossis
    release: bolo
  - name: toolbelt
    release: toolbelt
  - name: toolbelt-quick
    release: toolbelt
name: aws-proto-bolo
networks:
- name: bolo
  subnets:
  - cloud_properties:
      security_groups:
      - wide-open
      subnet: subnet-10f36466
    dns:
    - 10.4.0.2
    gateway: 10.4.1.1
    range: 10.4.1.0/24
    reserved:
    - 10.4.1.2   - 10.4.1.3
    - 10.4.1.4 - 10.4.1.63
    - 10.4.1.80 - 10.4.1.254
    static:
    - 10.4.1.65 - 10.4.1.68
  type: manual
releases:
- name: bolo
  sha1: cde24075f335e1f789fd15f8b09301da0afc87f2
  url: https://github.com/cloudfoundry-community/bolo-boshrelease/releases/download/v0.2.1/bolo-0.2.1.tgz
  version: 0.2.1
- name: toolbelt
  sha1: 0ff09164d76223823cd30bd5592fcc6c58a2c28f
  url: https://bosh.io/d/github.com/cloudfoundry-community/toolbelt-boshrelease?v=3.2.10
  version: 3.2.10
resource_pools:
- cloud_properties:
    availability_zone: us-west-2a
    ephemeral_disk:
      size: 4096
      type: gp2
    instance_type: m3.medium
  name: small
  network: bolo
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    sha1: 58b80c916ad523defea9e661045b7fc700a9ec4f
    url: https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3262.4
    version: 3262.4
update:
  canaries: 1
  canary_watch_time: 3000-120000
  max_in_flight: 50
  serial: false
  update_watch_time: 3000-120000

